spring.application.name=techmentor-backend

# Database Configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/techmentor}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate Settings
spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=never
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Custom Business Properties
app.xp-por-acierto=10
app.meta-diaria-lecciones=2
app.zona-horaria=America/Lima

# JWT Configuration
app.jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250655368566D5971}
app.jwt.expiration-ms=86400000
